from turtle import *
hideturtle()
Screen().bgcolor("yellow")
color('red')
fillcolor('green')
begin_fill()
penup()
goto(200,-200)
pendown()
forward(200)
right(90)
forward(200)
right(90)
forward(200)
right(90)
forward(200)
end_fill()